### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by avishkar7** [joegog/personality-detection-text#14]
Hi, 
I looked into running my own GloVe model but I couldn't access the Stanford link provided in the README. Regardless, I would love to use your repo for my project. Please let me know how you would like the citation to be.

**Comment by jkwieser** [comment]
Hi Avishkar,
thanks for reaching out.

The Stanford glove models are these - i think they are still available at:
https://nlp.stanford.edu/projects/glove/

Download pre-trained word vectors

   - Pre-trained word vectors. This data is made available under the Public
   Domain Dedication and License
<http://opendatacommons.org/licenses/pddl/> v1.0
   whose full text can be found at:
   http://www.opendatacommons.org/licenses/pddl/1.0/.
   - Wikipedia 2014 <http://dumps.wikimedia.org/enwiki/20140102/> + Gigaword
      5 <https://catalog.ldc.upenn.edu/LDC2011T07> (6B tokens, 400K vocab,
      uncased, 50d, 100d, 200d, & 300d vectors, 822 MB download):
      glove.6B.zip <https://nlp.stanford.edu/data/glove.6B.zip>
      - Common Crawl (42B tokens, 1.9M vocab, uncased, 300d vectors, 1.75
      GB download): glove.42B.300d.zip
      <https://nlp.stanford.edu/data/glove.42B.300d.zip>
      - Common Crawl (840B tokens, 2.2M vocab, cased, 300d vectors, 2.03 GB
      download): glove.840B.300d.zip
      <https://nlp.stanford.edu/data/glove.840B.300d.zip>
      - Twitter (2B tweets, 27B tokens, 1.2M vocab, uncased, 25d, 50d,
      100d, & 200d vectors, 1.42 GB download): glove.twitter.27B.zip
      <https://nlp.stanford.edu/data/glove.twitter.27B.zip>


I'm happy and grateful if you cite my work- i also love it if you give the
repo a "star" on github :)

Citation Format:

Wieser, Johannes K. (2020). Personality Prediction from Text. GitHub.
Available at: https://github.com/jkwieser/personality-prediction-from-text

THank you very much, Avishkar.

If you have further questions, just let me know.

Best
Johannes
