### ISSUE TITLE
Location of the pickled files of cEXT, cNEU, cAGR, cCON, cOPN

### ISSUE THREAD

**Issue by ushadi97** [joegog/personality-detection-text#2]
Hi @jkwieser,

Can I know, from where did you pickle the (write) cEXT, cNEU, cOPN , ..... I can only see the loading of these files in predict.py

Thanks & Regards

**Comment by jkwieser** [comment]
Hi @ushadi97,

it is pickled on several points depended on which model and the prediction power.

for using bags of words see model_bow.ipynb
for using GloVe see model_glove.ipynb

after the training of the algorithm the best performing classifier were pickled. they are later loaded and used to predict in predict.ipynb

thanks for your question

**Comment by jkwieser** [comment]
closed after answer.
