### ISSUE TITLE
How do I achieve the score measures of each personality scale?

### ISSUE THREAD

**Issue by reachyou91** [joegog/personality-detection-text#4]
The current results only provides a list containing binary measure for each personality scales. How can I get score measures from your code? Thanks in advance!

As shown below in your description
![image](https://user-images.githubusercontent.com/25308509/122965253-ffaada00-d355-11eb-8557-580981d30107.png)

**Comment by jkwieser** [comment]
Hi reachyou91,
the input data does not provide percentiles (0-100) it only provides a
binary indication weather a trait is significant or not (0 or 1).
therefore the model can only provide binary trait results.
i hope this is what you are referring to.
if you like the project I'd love to receive a github star (like) 😀
if you have further questions, just reach out to me.
have a great day,
best
Johannes

**Comment by reachyou91** [comment]
Thank you for your clear explanation.
